sudo: false

jobs:
  include:
    - stage: unit tests
      script: echo one
    - stage: unit tests
      script: echo two
    - stage: deploy to staging
      script: skip
    - stage: test staging
    - stage: deploy to production
      script: echo ok 
        
